{
    "name": "Account State Change Registry",
    "version": "18.0.1.0.0",
    "summary": "Registro de cambios de estado para facturas",
    "description": "Hereda account.move para registrar cambios en state.",
    "author": "Carlos Eduardo Salinas Honduras",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": [
        "account",
        "state_change_registry",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/mail_template_data.xml",
        "views/state_change_registry_views.xml",
        "views/account_move_views.xml",
        "wizard/state_change_registry_report_wizard_views.xml",
        "views/menus.xml",
        #"reports/account_move_state_change_registry_report.xml",
        "reports/account_move_state_change_registry_report_inherit.xml",
    ],
    "installable": True,
    "application": False,
}
